### ISSUE TITLE
export MMD file of current diagram?

### ISSUE THREAD

**Issue by AndrewKoransky** [h0lg/netAmermaid#1]
Would like to be able to export the automatically generated MMD diagram so I can tweak it and add it to our project documentation.

PS Just discovered this project, linked from https://github.com/mermaid-js/mermaid/issues/3188 (a problem I was having). Thanks for creating this project. Super helpful.

**Comment by h0lg** [comment]
Hey @AndrewKoransky,

I'm happy you find it helpful :) The next version is in the works. I can include an additional export option for `.mmd`, sure.

For now, open up your browser's **console** where the diagram lingo that is fed into mermaid is **logged at info level**. 
You can copy it from there, tweak it to your liking and save it as `.mmd`.

If you think any of the customizations you're doing can be automated, if the info you're adding can be extracted from your .dll, its debug/documentation metadata or dependencies - let me know here. If you want to brainstorm or ask questions, use the [discussions](https://github.com/h0lg/netAmermaid/discussions).
